name: Task 📝
description: Request a new task
title: "[Task]: "
labels: [“task"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description 
      description: What is the task you want accomplished and why.
      placeholder: Tell us what you want to see!
    validations:
      required: true
  - type: input
    id: planning-document-link
    attributes:
      label: Link to planning document
      description: Link to relevant document from planning stage, f.ex. google doc, google sheets etc.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Screenshots? References? You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
